### ISSUE TITLE
Light Scan Sim Error

### ISSUE THREAD

**Issue by borchr27** [neobotix/neo_simulation#26]
Im having an issue that may or may not just be setup related. Im trying to get the **mp_500** to run in **neo_workshop** autonomously by  running the ```roslaunch neo_simulation mp_500_autonomous_navigation.launch``` command and I have followed the instructions posted [here](https://www.neobotix-docs.de/ros/ros1/simulation.html) but Im getting these errors:

- ERROR: cannot launch node of type [light_scan_sim/visualize_segment_list.py]: light_scan_sim
- ERROR: cannot launch node of type [light_scan_sim/light_scan_sim_node]: light_scan_sim

If this is not the correct place for this please let me know!

**Comment by padhupradheep** [comment]
Thanks for reporting, that indeed is an issue, we will fix it and will update here.

**Comment by padhupradheep** [comment]
Fixed in the recent commit! Could you now please retry?

**Comment by borchr27** [comment]
Ok I tried ```roslaunch neo_simulation mp_500_autonomous_navigation.launch```  after running a ```catkin clean``` and a ```catkin build``` and I'm still getting the same two errors: 
- ERROR: cannot launch node of type [light_scan_sim/visualize_segment_list.py]: light_scan_sim
- ERROR: cannot launch node of type [light_scan_sim/light_scan_sim_node]: light_scan_sim

Im also getting a warning that may be unrelated but that I'm also trying to resolve:
- [WARN] [1647355657.845816992]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: canTransform: target_frame map does not exist. canTransform: source_frame base_link does not exist.. canTransform returned after 0.100305 timeout was 0.1.

My main goal is to get the mp_500 running autonomously with gazebo and rviz running

**Comment by padhupradheep** [comment]
Could you retry please? Missing ">" should be the issue.

**Comment by borchr27** [comment]
> Could you retry please? Missing ">" should be the issue.

Ya I fixed that first and tried it.

**Comment by borchr27** [comment]
Ok I missed what you said there, commenting out that code does fix the original error I was getting.

**Comment by padhupradheep** [comment]
Do you face anyother issues?

**Comment by borchr27** [comment]
The other issue Im facing is when I run ```roslaunch neo_simulation simulation.launch``` with the launch file shown below which is basically just the unchanged file. I get an error in rviz that my robot cant be found and my robot is not navigating in the neo_workshop.world world. Shown in the image below.

Meanwhile my terminal is outputting this constantly when I try to run the above roslaunch
- Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame mp_500_fixed_wheel_right_link at time 12192.656000 according to authority unknown_publisher

Thanks for the help so far!

![image](https://user-images.githubusercontent.com/30349201/158414895-162bfffd-1c1b-4fa4-bc80-3a6123065d1c.png)


---

```
<?xml version="1.0" encoding="UTF-8"?>
<launch>

  <!--set to the required robot type and world-->
  <!-- <arg name="robot_type" default="mpo_700"/> -->
  <arg name="robot_type" default="mp_500"/>
  <arg name="robot_world" default="neo_workshop.world"/>
  <!--arg name="world_name" value=""/-->

  <!--To launch RVIZ set the value to true-->
  <arg name="rviz" default="true"/>


  <!--To launch move base set the value to true-->
  <arg name="autonomous_navigation" default="true"/>

<!---=================================================================================================================================================================-->

  <!-- Basic Simulation -->
  <include file="$(find neo_simulation)/launch/$(arg robot_type)/$(arg robot_type)_simulation_basic.launch">
	<arg name="world_name_global" value="$(find neo_simulation)/worlds/$(arg robot_world)"/>
  </include>

  <!-- Autonomous Navigation -->
  <group if="$(arg autonomous_navigation)">
      <include file="$(find neo_simulation)/launch/$(arg robot_type)/$(arg robot_type)_autonomous_navigation.launch"/>
  </group>

  <!-- RVIZ -->
  <group if="$(arg rviz)">
      <include file="$(find neo_simulation)/launch/$(arg robot_type)/$(arg robot_type)_rviz.launch"/>
  </group>

<!---=================================================================================================================================================================-->


</launch>
```

**Comment by padhupradheep** [comment]
retry with the new changes please. you can safely ignore the warnings.

**Comment by borchr27** [comment]
Noob question here sorry, how do I set the MAP_NAME variable in the acml.launch file?

```
RLException: while processing ~neo_simulation/launch/mp_500/mp_500_autonomous_navigation.launch:
while processing ~/neo_simulation/config/mp_500/amcl/mp_500_amcl.launch:
Invalid <arg> tag: environment variable 'MAP_NAME' is not set. 
```

**Comment by padhupradheep** [comment]
you need to set it using `	export MAP_NAME=neo_track1` from your command line! Please follow the documentations further!
